# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

# Force use of Java 17 for Gradle
org.gradle.java.home=C:\\Program Files\\Java\\jdk-17

# Override path check for non-ASCII characters in project path
android.overridePathCheck=true
